server:
  port: 8081
openai:
  apikey:  dummy

spring:
  # Datasource 설정
  datasource:
    username: admin
    password: zxcv1234
    url: jdbc:mariadb://j9a106.p.ssafy.io:3306/oasys
    hikari:
      maximum-pool-size: 10
      connection-init-sql: SELECT 1
      connection-timeout: 5000
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: true

  jpa:
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: none
  config:
    import: "file:./src/main/resources/env.yml"

logging:
  level:
    org.hibernate.type.descriptor.sql: trace